apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: flask-postgres
  namespace: postgres # 👈 runs in its own namespace
spec:
  teamId: "flask"
  volume:
    size: 10Gi
  numberOfInstances: 1
  users:
    flaskuser:
    # database user
    - superuser
    - createdb
  databases:
    flaskdb: flaskuser
  postgresql:
    version: "14"
