apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flask-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/sadebo/aks-postgres-app.git'
    targetRevision: main
    path: manifests/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
