apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  labels:
    app: flask-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: parallelacr2901.azurecr.io/flask-app:latest
        imagePullPolicy: Always
        env:
        - name: DB_HOST
          value: demo-cluster.default.svc.cluster.local
        - name: DB_NAME
          value: appdb
        - name: DB_USER
          value: app_user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: password
        - name: DB_PORT
          value: "5432"
        ports:
        - containerPort: 5000
