apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-operator
  namespace: default
  labels:
    app: postgres-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-operator
  template:
    metadata:
      labels:
        app: postgres-operator
    spec:
      containers:
      - name: operator
        image: registry.opensource.zalan.do/acid/postgres-operator:v1.12.0
        ports:
        - containerPort: 8080
