name: Build & Deploy App - Flask with Postgres

on:
  push:
    branches:
    - main
    paths:
    - 'app/**'
    - 'manifests/**'
    - '.github/workflows/build.yaml'
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Export ARM env
      run: |
        echo "ARM_CLIENT_ID=${{ fromJson(secrets.AZURE_CREDENTIALS).clientId }}" >> $GITHUB_ENV
        echo "ARM_CLIENT_SECRET=${{ fromJson(secrets.AZURE_CREDENTIALS).clientSecret }}" >> $GITHUB_ENV
        echo "ARM_TENANT_ID=${{ fromJson(secrets.AZURE_CREDENTIALS).tenantId }}" >> $GITHUB_ENV
        echo "ARM_SUBSCRIPTION_ID=${{ fromJson(secrets.AZURE_CREDENTIALS).subscriptionId }}" >> $GITHUB_ENV

    - name: ACR Login
      run: az acr login --name myaksacr01

    - name: Build & Push Docker Image
      uses: docker/build-push-action@v4
      with:
        context: ./app
        push: true
        tags: myaksacr01.azurecr.io/flask-app:${{ github.sha }}

    - name: Update manifests with new image tag
      run: |
        sed -i "s|image: .*|image: myaksacr01.azurecr.io/flask-app:${{ github.sha }}|" manifests/base/deployment.yaml
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git add manifests/base/deployment.yaml
        git commit -m "Update flask-app image to ${{ github.sha }}"
        git push

  validate:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Export ARM env
      run: |
        echo "ARM_CLIENT_ID=${{ fromJson(secrets.AZURE_CREDENTIALS).clientId }}" >> $GITHUB_ENV
        echo "ARM_CLIENT_SECRET=${{ fromJson(secrets.AZURE_CREDENTIALS).clientSecret }}" >> $GITHUB_ENV
        echo "ARM_TENANT_ID=${{ fromJson(secrets.AZURE_CREDENTIALS).tenantId }}" >> $GITHUB_ENV
        echo "ARM_SUBSCRIPTION_ID=${{ fromJson(secrets.AZURE_CREDENTIALS).subscriptionId }}" >> $GITHUB_ENV

    - name: Get AKS Credentials
      run: az aks get-credentials --resource-group rg-aks-postgres --name aks-postgres-cluster --overwrite-existing

    - name: Check cert-manager pods
      run: |
        kubectl rollout status deployment/cert-manager -n cert-manager --timeout=120s
        kubectl rollout status deployment/cert-manager-webhook -n cert-manager --timeout=120s
        kubectl rollout status deployment/cert-manager-cainjector -n cert-manager --timeout=120s

    - name: Check ingress-nginx pods
      run: kubectl rollout status deployment/ingress-nginx-controller -n ingress-nginx --timeout=120s

    - name: Verify TLS secrets
      run: |
        kubectl get secret argocd-tls -n argocd || exit 1
        kubectl get secret flask-tls -n dev || exit 1

    - name: Smoke test Flask healthz
      run: curl -vk https://flask.example.com/healthz
