name: Infra

on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
    - 'terraform/**'

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.7.0

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Terraform Init
      run: terraform -chdir=terraform init -input=false

    - name: Terraform Apply
      run: terraform -chdir=terraform apply -auto-approve
