name: Provision Infra + Build & Deploy App

on:
  push:
    branches:
    - main
    paths:
    - 'terraform/**'
    - 'app/**'
    - 'manifests/**'
    - '.github/workflows/deploy.yaml'
  workflow_dispatch:


permissions:
  contents: write

jobs:
  infra:
    name: Provision Infrastructure (AKS + ACR)
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.9.7

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Export ARM env
      run: |
        echo "ARM_CLIENT_ID=${{ fromJson(secrets.AZURE_CREDENTIALS).clientId }}" >> $GITHUB_ENV
        echo "ARM_CLIENT_SECRET=${{ fromJson(secrets.AZURE_CREDENTIALS).clientSecret }}" >> $GITHUB_ENV
        echo "ARM_TENANT_ID=${{ fromJson(secrets.AZURE_CREDENTIALS).tenantId }}" >> $GITHUB_ENV
        echo "ARM_SUBSCRIPTION_ID=${{ fromJson(secrets.AZURE_CREDENTIALS).subscriptionId }}" >> $GITHUB_ENV

    - name: Terraform Init
      run: terraform -chdir=terraform init -input=false

    - name: Terraform Apply Infra
      run: terraform -chdir=terraform apply -auto-approve \ -target=azurerm_resource_group.rg \ -target=azurerm_container_registry.acr \ -target=azurerm_kubernetes_cluster.aks

  addons:
    name: Install Addons (ArgoCD, Ingress, Cert-manager, Postgres Operator)
    runs-on: ubuntu-latest
    needs: infra

    steps:
    - uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.9.7
